site_name: strplus
site_author: Silvio Liborio
site_description: >-
  Extend your string powers with Str+  
site_url: https://wiseupdata.github.io/strplus/index.html

# Copyright
copyright: Copyright &copy; 2023 - 2023 Silvio Liborio

theme:
  name: 'material'
  # custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: strplusTheme
    accent: pink
    toggle:
      icon: material/brightness-4
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    primary: pink
    accent: lime
    toggle:
      icon: material/weather-night
      name: "Switch to dark mode"
  font:
    text: Roboto
    code: Roboto Mono
    features:
      - search.suggest
      - search.highlight
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - navigation.footer
      - navigation.indexes
      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - footnotes
    # - toc.integrate
  # logo: 'logo-white.svg'
  # favicon: 'favicon.png'
  icon:
    repo: fontawesome/brands/github-alt
  language: en
repo_name: wiseupdata/strplus
repo_url: https://github.com/wiseupdata/strplus


extra_css:
  - stylesheets/strplusTheme.css
# - 'extra/tweaks.css'
# extra_javascript:
# - 'extra/redirects.js'

nav:
# - Index: index.md
- Str+: strplus/

plugins:
  - search 
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index 
  - mkdocstrings:
      handlers:
        python:
          paths: [strplus]

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Pages
- admonition
- pymdownx.highlight
- pymdownx.extra
# - pymdownx.emoji:
#     emoji_index: !!python/name:materialx.emoji.twemoji
#     emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true


# language options
extra:
  alternate:
    - link: /
      name: English