[tool.poetry]
name = "strplus"
version = "0.0.1"
description = ""
authors = ["SilvioLiborio <silvio.liborio@wiseupdata.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
