site_name: Extend your string powers with Str+

theme:
  name: "material"
  palette:
    primary: pink

nav:
- Index: index.md
- Str+: strplus/

plugins:
  - search 
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index 
  - mkdocstrings:
      handlers:
        python:
          paths: [strplus]