site_name: strplus

nav:
- index: index.md
- Code Reference: strplus/

plugins:
  - search 
  - literate-nav:
      nav_file: SUMMARY.md 
  - mkdocstrings:
      handlers:
        python:
          paths: [strplus]